theme: jekyll-theme-minimal

url: https://www.early-morn-prog.org
baseurl: /

title: 早朝プログラマ

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

timezone: Japan

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge